config/routes.rb
HackerEngine::Application.routes.draw do

  match '/help',   to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact' => 'contact#new', :as => 'contact', :via => :get
  match '/contact' => 'contact#create', :as => 'contact', :via => :post

  root :to => 'pages#home'

  resources :orders

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/order.rb
class Order < ActiveRecord::Base
  PRODUCT_PRICE_IN_CENTS = 10000

  attr_accessor :stripe_card_token

  validates :email, presence: true
 # validates :github_username, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  def save_with_payment
    if valid?
      charge = Stripe::Charge.create(description: email, card: stripe_card_token, amount: PRODUCT_PRICE_IN_CENTS, currency: 'usd')
      self.stripe_charge_id = charge.id
      save!
    end
  rescue Stripe::InvalidRequestError => error
    logger.error "Stripe error while creating customer: #{error.message}"
    errors.add :base, "There was a problem with your credit card."
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @order = Order.new
  end

  def create
    @order = Order.new(params[:order])

    if @order.save_with_payment
      # To enable digital download delivery, uncomment the line below and see lib/download_deliverer.rb
       DownloadDeliverer.deliver_download

      redirect_to order_path(@order)
    else
      render :new
    end
  end

  def show
    @order = Order.find(params[:id])
  end

  private

  def add_collaborator
    CollaboratorAdder.add(@order.github_username)
  end

  def deliver_download
    DownloadDeliverer.new(@order).deliver
  end
  
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def contact
  end
  
  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="description" content="Hacker Engine is a tricked-out Rails app for developers who want to sell digital goods.">
	<meta name="viewport" content="width=device-width; initial-scale=1.0">
	<title>Digital Download Engine | <%= yield(:title) %></title>
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "https://js.stripe.com/v1/", "application" %>
	<%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
	<%= csrf_meta_tags %>
	<!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
	<script type="text/javascript">

	var _gaq = _gaq || [];
	_gaq.push(['_setAccount', '']);
	_gaq.push(['_setDomainName', '']);
	_gaq.push(['_trackPageview']);

	(function() {
		var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		})();

		</script>
	</head>

	<body>
		<%= render 'shared/banner' %>

		<div class="container">
			<%= render 'shared/flashes' %>
			<%= yield %>

		</div>

	</body>
	</html>

app/views/orders/_kissmetrics_purchase_tracking.html.erb
<script type="text/javascript">
  _kmq.push(['identify', '<%= @order.email %>']);
  _kmq.push(['record', 'Purchased']);
  _kmq.push(['billed', 149.00]);
</script>

app/views/orders/_kissmetrics_viewed_checkout_tracking.html.erb
<script type="text/javascript">
  _kmq.push(['record', 'Viewed Checkout']);
</script>

app/views/orders/new.html.erb
<% provide(:title, 'Purchase') %>
<div class="page-header">
	<h1>Purchase Me Some New Shoes</h1>
	<h2>A one time cost of $149</h2>

	<ul>
		<li>Once you submit payment, you'll receive access to a my house with the full source code.</li>
		<li>You are free to use the code for as many projects as you choose.</li>
		<li>You'll get immediate access to bug fixes and improvements as the project grows.</li>
	</ul>
</div>

<div class="row">
	<div class="span8">
		<div class="well-light">
		<%= form_for @order, html: { class: 'form-horizontal' } do |f| %>
		<fieldset>

			<% if @order.errors.any? %>
			<div class="error_messages">
				<h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>
				<ul>
					<% @order.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
			<% end %>

			<div id="stripe_error" class="alert" style="display: none">
				<noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
			</div>

			<%= f.hidden_field :stripe_card_token %>

			<legend>Your information</legend>

			<div class="control-group">
				<%= f.label :first_name, class: 'control-label' %>
				<div class="controls">
					<%= f.text_field :first_name, class: 'span4' %>
				</div>
			</div>

			<div class="control-group">
				<%= f.label :last_name, class: 'control-label' %>
				<div class="controls">
					<%= f.text_field :last_name, class: 'span4' %>
				</div>  
			</div>

			<div class="control-group">
				<%= f.label :email, class: 'control-label' %>
				<div class="controls">
					<%= f.text_field :email, class: 'span4' %>
				</div>  
			</div>


		</fieldset>

		<fieldset>
			<legend>Billing information</legend>

			<div class="control-group">
				<%= label_tag :card_number, "Card Number", class: 'control-label' %>
				<div class="controls">
					<%= text_field_tag :card_number, nil, name: nil, class: 'span4' %>
					<p class="help-block">Visa, MasterCard, American Express, Discover, or JCB.</p>
					<p class="help-block">Payments are <strong>processed by Stripe through SSL</strong>. <br /> Your credit card details never hit our server.</p>
				</div>
			</div>

			<div class="control-group">
				<%= label_tag :card_code, "CVV Number", class: 'control-label' %>
				<div class="controls">
					<%= text_field_tag :card_code, nil, name: nil, class: 'span1' %>
				</div>
			</div>

			<div class="control-group">
				<%= label_tag :card_month, "Expiration Date" %>
				<div class="controls">
					<%= select_month nil, { add_month_numbers_true: true }, { name: nil, id: "card_month", class: 'span2' }%>
					<%= select_year nil, { start_year: Date.today.year, end_year: Date.today.year+15 }, { name: nil, id: "card_year", class: 'span1' }%>
				</div>
			</div>

			<div class="form-actions">
			<%= f.submit "Purchase now", class: "span4 btn btn-large btn-primary purchase" %>
		</div>

	</fieldset>

	<p class="quiet-text">If you're unsatisfied with Hacker Engine for any reason, we'll happily refund your money.</p>
	<p class="quiet-text">Got questions that aren't answered here? <%= mail_to 'support@hackerengine.com', 'Email us' %>, or ask on <%= link_to 'twitter', 'http://twitter.com/hackerengine' %>.</p>
	<% end %>
</div>
</div>

<div class="span4">
	<div class="alert alert-success">
		<h2><span class='grey'>Heading</span> One</h2>

		<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>
		<p> It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
	</div>
</div>


</div>
<%= render 'shared/footer' %>

app/views/orders/show.html.erb
<h1>Your payment was successful.</h1>

<p>Thanks so much for purchasing our product. You should receive an email with download instructions momentarily.</p>

<p>If you don't receive the email within an hour, don't hesitate to <%= mail_to 'ben.orenstein@gmail.com', 'email me' %>.</p>

app/views/pages/_kissmetrics_landing_page_tracking.html.erb
<script type="text/javascript">
  _kmq.push(['record', 'Viewed Landing Page']);
</script>

app/views/pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="container">
	<header class="hero-unit">
		<h1>Digital Download Engine</h1>
		<p class="masthead">a self hosted <span class="grey">(heroku)</span> digital download website framework</p>
	</header>


<div class="row">
	<div class="span12">
	<div class="alert alert-info blue-banner">
		
		<h1><span class="black">The</span> Stack</h1>
		
	</div>
	</div>
</div>


<div class="row">
	<div class="span8">
		<div class="row">
			<div class="span4">
				<h2><span class="label label-info">one</span> Heroku App Hosting</h2>
				<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
				<h2><span class="label label-info">three</span> Hacker Engine</h2>
				<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
			</div>
			<div class="span4">
				<h2><span class="label label-info">two</span> Ruby on Rails</h2>
				<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
				<h2><span class="label label-info">four</span> Twitter Bootstrap</h2>
				<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
			</div>
		</div>
	</div>
	<div class="span4">
		<div class="alert alert-info">
			<h2><span class='grey'>Target</span> Audience</h2>

			<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
			<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
		</div>
	</div>
</div>


<div class="row">
	<div class="span8">
		<div class="row">
			<div class="span4">
				<h2><span class="label label-info">five</span> Stripe Payments</h2>
				<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
			</div>
			<div class="span4">
				<h2><span class="label label-info">six</span> Fetchapp Delivery</h2>
				<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
			</div>
		</div>
	</div>

	<div class="span4">
		<h2><span class="label label-info">seven</span> Kissemetrics Analytics</h2>
		<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
	</div>
</div>


<br />

<div class="well">
	<div class="row">
		<div class="span8 form-horizontal">
			<h1>Getting started now. It's <span class='grey'>easy peasy</span> - </h1>
		</div>
			<%= link_to 'Purchase Now', new_order_path, class: 'span3 btn btn-primary btn-large call-to-action' %>
	</div>
</div>

<%= render 'shared/footer' %>



</div> <!-- /container -->

app/views/products/intro_to_vimscript.html.erb
<h1>Introduction to Vimscript</h1>

<%= link_to 'Purchase', new_order_path, class: 'purchase' %>

app/views/shared/_banner.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
     
      <div class="nav-collapse">
		 <%= link_to '{digital download engine}', root_path, class: 'brand' %>
	
        <ul class="nav">
          <li><%= link_to "About", '/about' %></li>
          <li><%= link_to "Help", '/help' %></li>
          <li><%= link_to "Contact", '/contact' %></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% unless flash[:notice].blank? %>
  <div class="alert-message info">
    <%= content_tag :div, flash[:notice] %>
  </div>
<% end %>

<% unless flash[:error].blank? %>
  <div class="alert-message error">
    <%= content_tag :div, flash[:error] %>
  </div>
<% end %>

<% unless flash[:alert].blank? %>
  <div class="alert-message warning">
    <%= content_tag :div, flash[:alert] %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
	<br />
	<hr>
<!--	<div class='row'>

		<div class='span4'>
			<div class='well-footer'>
				<h3>Links</h3>
				<ul>
					<li> <a href="http://#">Hacker-Engine</a></li>
					<li><a href="http://#">FetchApp</a></li>
					<li> <a href="http://#">Twitter bootstrap</a></li>
					<li> <a href="http://#">Stripe</a></li>
					<li> <a href="http://#">Ruby on Rails</a></li>

				</ul>
			</div>
		</div>

		<div class='span4'>
			<div class='well-footer'>

				<h3>Some footer info</h3>
				<ul>
					<li>Once you submit payment, you'll receive access to a my house with the full source code.</li>
					<li>You are free to use the code for as many projects as you choose.</li>
					<li>You'll get immediate access to bug fixes and improvements as the project grows.</li>
				</ul>
			</div>
		</div>

		<div class='span4'>
			<div class='well-footer'>

				<h3>Some footer info</h3>
				<ul>
					<li>Once you submit payment, you'll receive access to a my house with the full source code.</li>
					<li>You are free to use the code for as many projects as you choose.</li>
					<li>You'll get immediate access to bug fixes and improvements as the project grows.</li>
				</ul>
			</div>
		</div>

	</div> -->

	<div class='row'>
		<div class='span12'><br />
			<p class='pull-right'>&copy; Digital Download Engine 2012</p>
			</div>
		</div>


	</div>  
</footer>

app/views/shared/_kissmetrics.html.erb
<script type="text/javascript">
var _kmq = _kmq || [];
  function _kms(u){
    setTimeout(function(){
    var s = document.createElement('script'); var f = document.getElementsByTagName('script')[0]; s.type = 'text/javascript'; s.async = true;
    s.src = u; f.parentNode.insertBefore(s, f);
    }, 1);
  }
  _kms('//i.kissmetrics.com/i.js');_kms('//doug1izaerwt3.cloudfront.net/<%= KISSMETRICS_API_KEY %>.1.js');
</script>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<div class="container">
	<div class="page-header">
		<h1>A Little About Us</h1>

		<h2>and a little about what we do</h2>
	</div>

	<div class="row">
		<div class="span6">
			<h2>The Product</h2>

			<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris
				condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec
				sed odio dui.</p>

				<p>Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a
					galley of type and scrambled it to make a type specimen book.</p>
				</div>
				<div class="span6">
					<h2>The Vision</h2>

					<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris
						condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec
						sed odio dui.</p>

						<p>Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a
							galley of type and scrambled it to make a type specimen book.</p>
						</div>
					</div>
					<!-- /row -->
						<hr>
					<div class="row">
						<div class="span12">
							<h2>The Team</h2><br/>
						</div>
					</div>
					<div class="row">
						<div class="span12">
							<ul class="thumbnails">
								<li class="span3">
									<div class="thumbnail about">
										<img src="/assets/260x180.gif" alt="">

										<div class="caption">
											<h5>Mr. Miyagi</h5>

											<p>"Wax on. Wax off." "Use head for something other than target."</p>
										</div>
									</div>
								</li>
								<li class="span3">
									<div class="thumbnail about">
										<img src="/assets/260x180.gif" alt="">

										<div class="caption">
											<h5>Daniel-San</h5>

											<p>When he is not complaining, Daniel does a great Crane.</p>
										</div>
									</div>
								</li>
								<li class="span3">
									<div class="thumbnail about">
										<img src="/assets/260x180.gif" alt="">

										<div class="caption">
											<h5>Ali Mills</h5>

											<p>Ali likes to hang out with Daniel when she's not at UCLA football games.</p>
										</div>
									</div>
								</li>
								<li class="span3">
									<div class="thumbnail about">
										<img src="/assets/260x180.gif" alt="">

										<div class="caption">
											<h5>Lucille Larusso</h5>

											<p>A great manager and an awesome single mom.</p>
										</div>
									</div>
								</li>
							</ul>
						</div>
					</div>
					<!-- /row -->

					<%= render '/shared/footer' %>


				</div><!-- /container -->

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>

<div class="container">
	<div class="page-header">
		<h1>Need Help?</h1>
		<h2>questions and answers and short tutorials</h2>
	</div>
	<div class='row'>
		<div class="span8">
			<div class="accordion" id="accordion2">
				<div class="accordion-group">
					<div class="accordion-heading">
						<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
							Collapsible Group Item #1
						</a>
					</div>
					<div id="collapseOne" class="accordion-body in collapse" style="height: auto; ">
						<div class="accordion-inner">
							Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
						</div>
					</div>
				</div>
				<div class="accordion-group">
					<div class="accordion-heading">
						<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
							Collapsible Group Item #2
						</a>
					</div>
					<div id="collapseTwo" class="accordion-body collapse">
						<div class="accordion-inner">
							Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
						</div>
					</div>
				</div>
				<div class="accordion-group">
					<div class="accordion-heading">
						<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseThree">
							Collapsible Group Item #3
						</a>
					</div>
					<div id="collapseThree" class="accordion-body collapse">
						<div class="accordion-inner">
							Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
						</div>
					</div>
				</div>



				<div class="accordion-group">
					<div class="accordion-heading">
						<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseFour">
							Collapsible Group Item #4
						</a>
					</div>
					<div id="collapseFour" class="accordion-body collapse">
						<div class="accordion-inner">
							Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
						</div>
					</div>
				</div>



				<div class="accordion-group">
					<div class="accordion-heading">
						<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseFive">
							Collapsible Group Item #5
						</a>
					</div>
					<div id="collapseFive" class="accordion-body collapse">
						<div class="accordion-inner">
							Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
						</div>
					</div>
				</div>



				<div class="accordion-group">
					<div class="accordion-heading">
						<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseSix">
							Collapsible Group Item #6
						</a>
					</div>
					<div id="collapseSix" class="accordion-body collapse">
						<div class="accordion-inner">
							Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
						</div>
					</div>
				</div>



				<div class="accordion-group">
					<div class="accordion-heading">
						<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseSeven">
							Collapsible Group Item #7
						</a>
					</div>
					<div id="collapseSeven" class="accordion-body collapse">
						<div class="accordion-inner">
							Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class='span4'>
			<div class="alert alert-info">
				<h2><span class='grey'>Helpful</span> Resources</h2> 
				<ul>
					<li><a href="http://api.rubyonrails.org/">Rails: Complete API</a></li>
					<li><a href="https://help.github.com/">Github help</a></li>
					<li><a href="http://twitter.github.com/bootstrap/">Twitter Bootstrap</a></li>
					<li><a href="https://stripe.com/">Stripe</a></li>
					<li><a href="http://www.fetchapp.com/">Fetchapp</a></li>
					<li><a href="http://www.heroku.com/">Heroku</a></li>
				</ul>	
			</div>  
		</div>         
	</div>         

</div>

<%= render 'shared/footer' %>


<!-- /container -->